#!/usr/bin/env python
# Dogtail demo script
__author__ = 'David Malcolm <dmalcolm@redhat.com>'

# Test composing and sending an email
#
# Assumes evolution is configured and is running
#

from dogtail.apps.wrappers.evolution import *

from datetime import datetime

#testName = "UntitledDogtailTest"
testRunId = "%s"%(datetime.now().isoformat())

evo = EvolutionApp()
composer = evo.composeEmail()
composer.to = "YOUR-EMAIL-ADDRESS-HERE"
composer.subject = "Test email (generated by Dogtail).  Testrun: %s)"%testRunId
composer.body = "This is a test email generated by Dogtail."
composer.send()
