#!/usr/bin/python

from dogtail.procedural import *
from time import sleep

focus.application('gnome-panel')
click('System')
click('Log Out .*')
sleep(1)
focus.application('gnome-session')
click('Log Out')
