#!/usr/bin/python
"""
dogtail-run-headless

This script runs a session within an X server, allowing dogtail scripts to be
run on systems with no graphic cards, among other things. Currently it can 
only start GNOME sessions.

Scripts are run in the current directory. After they are finished, dogtail can
optionally log out of the session, which will also termninate the X server.
"""

from optparse import OptionParser
from dogtail import sessions
import sys
import os.path

def findXServers(path = "/usr/bin"):
    l = [os.path.join(path, f) for f in os.listdir(path) if f[0] == 'X']
    s = set(os.path.realpath(p) for p in l)
    return list(s)

def parse():
    parser = OptionParser()
    parser.add_option("-s", "--session", dest = "session", type = "choice",
            choices = ["GNOME"], help = "which session to use")
    parser.add_option("-x", "--x-server", dest = "xserver", type = "choice",
            choices = findXServers(), help = "which X server to use")
    parser.add_option("-n", "--no-terminate", action = "store_false", 
            dest = "terminate", 
            help = "don't terminate the session when the script ends")
    parser.set_defaults(session = "GNOME", terminate = True)
    options, args = parser.parse_args()
    return options, args

def main():
    options, args = parse()
    if options.session == "GNOME":
        session = sessions.GNOMESession(script = " ".join(args), logout = options.terminate)
    if options.xserver: session.xserver.binary = options.xserver
    pid = session.start()
    session.wait()
    sys.exit(session.scriptExitCode)

if __name__ == "__main__": main()
